### ISSUE TITLE
atmosphere-runtime from 2.6.x has osgi manifest import org.testng

### ISSUE THREAD

**Issue by hieplq** [Atmosphere/atmosphere#2424]
**Describe the bug**
atmosphere-runtime from 2.6.x has osgi manifest import org.testng and javax.jnlp
it look not good when binary request test framework

**Atmosphere Info**
  - version 2.6.x

**Comment by sennew** [comment]
Hi, 

Has this issue ever been resolved in any particular release?

**Comment by jfarcand** [comment]
@sennew waiting for a patch/pull request :-)

**Comment by jfarcand** [comment]
@sennew yes

**Comment by vogella** [comment]
AFAICS the testng requirement for OSGI is still present in the runtime. https://github.com/Atmosphere/atmosphere/pull/2465 has been created to fix that.
